<?php

namespace App\Filament\Resources\DynamicPromptResource\Pages;

use App\Filament\Resources\DynamicPromptResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Cache;

class EditDynamicPrompt extends EditRecord
{
    protected static string $resource = DynamicPromptResource::class;

    public function mount($record): void
    {
        if (!empty(request()->folder_id)){
            Cache::set('folder_id',request()->folder_id);
        }


        parent::mount($record); // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        return $this->previousUrl ?? $this->getResource()::getUrl('index');
    }

    protected function getActions(): array
    {
        return [
           // Actions\DeleteAction::make(),
        ];
    }
}
