<?php

namespace App\Filament\Resources\DynamicButtonResource\Pages;

use App\Filament\Resources\DynamicButtonResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Support\Actions\Modal\Actions\Concerns\CanCancelAction;
use Illuminate\Support\Facades\Cache;

class ListDynamicButtons extends ListRecords
{
    protected static string $resource = DynamicButtonResource::class;

    public function mount(): void
    {

        Cache::set('folder_id',request()->folder_id);
        parent::mount(); // TODO: Change the autogenerated stub
    }


    protected function getActions(): array
    {

        return [
            Actions\CreateAction::make()->url(route('filament.resources.dynamic-buttons.create')."?folder_id=".Cache::get('folder_id')),
            Actions\Action::make("Back")->label('Back')->url(route('filament.resources.folders.view',Cache::get('folder_id'))),
            ];
    }
}
