<?php

namespace App\Filament\Resources\CommandResource\Pages;

use App\Filament\Resources\CommandResource;
use App\Models\Folder;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Cache;

class EditCommand extends EditRecord
{
    protected static string $resource = CommandResource::class;

    public function mount($record): void
    {
        if (!empty(request()->folder_id)){
            Cache::set('folder_id',request()->folder_id);
        }


        parent::mount($record); // TODO: Change the autogenerated stub
    }


    /**
     * @param mixed $redirectTo
     */
    protected function getRedirectUrl(): string
    {
        return $this->previousUrl ?? $this->getResource()::getUrl('index');
    }



}
