<?php

namespace App\Filament\Resources\FolderResource\Pages;

use App\Filament\Resources\FolderResource;
use Filament\Forms\Components\Actions\Action;
use Filament\Pages\Actions;
use Filament\Pages\Dashboard;
use Filament\Resources\Pages\EditRecord;

class EditFolder extends EditRecord
{
    protected static string $resource = FolderResource::class;
   // protected static ?string $title =  'Customize Bot Layout';
    protected static ?string $breadcrumb = 'Customize';
    protected static ?string $backpage = 'Customize';

    public function getTitle(): string
    {

        if($this->record->parent_folder_id == null){
            return 'Edit project'; // TODO: Change the autogenerated stub
        }else{
            return 'Customize Bot Layout'; // TODO: Change the autogenerated stub
        }


    }



    protected function getActions(): array
    {
       return [

       ];

    }
    protected function getFormActions(): array
    {
      return parent::getFormActions();
    }

    protected function getRedirectUrl(): string
    {

        if (!empty($this->record->parent_folder_id)){
            return route('filament.resources.bot.view',$this->record->id);
        }
        return route('filament.resources.bot.viewProject',$this->record->id);
    }
}
