<?php

namespace App\Filament\Resources\FolderResource\Pages;

use App\Filament\Resources\FolderResource;
use Filament\Forms;
use Filament\Forms\Components\Actions\Action;
use Filament\Forms\Components\Select;
use Filament\Pages\Actions;
use Filament\Pages\Dashboard;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Cache;

class EditFolder extends EditRecord
{
    protected static string $resource = FolderResource::class;
   // protected static ?string $title =  'Customize Bot Layout';
    protected static ?string $breadcrumb = 'Customize';
    protected static ?string $backpage = 'Customize';

    public function mount($record): void
    {

        parent::mount($record); // TODO: Change the autogenerated stub
    }

    public function getTitle(): string
    {

        if($this->record->parent_folder_id == null){
            return 'Edit project'; // TODO: Change the autogenerated stub
        }else{
            return 'Customize Bot Layout'; // TODO: Change the autogenerated stub
        }


    }

    protected function afterSave(){

        if (!empty(!empty($this->getMountedActionForm())) && $this->getMountedActionForm()->getContext() == "Save and force translate"){
            $this->record->lang_all_column = null;
            $this->record->is_multi_lang = true;
            $this->record->save();

            dispatch(new \App\Jobs\EditFolder($this->record));
        }

    }



    protected function getActions(): array
    {
       return [

       ];

    }

//    protected function getFormActions(): array
//    {
//
//
////       $ss =   parent::getFormActions()[0]->requiresConfirmation()
////            ->modalHeading('Delete posts')
////            ->modalSubheading('Are you sure you\'d like to delete these posts? This cannot be undone.')
////            ->modalButton('Yes, delete them');
//        $ss = Action::make('update');
//       return [$ss];
//
//       return parent::getFormActions();
//    }

   protected function getFormActions(): array
   {

       $ss = [];
       array_push($ss,parent::getFormActions()[0]);

       array_push($ss,Actions\Action::make('Save and force translate')
           ->requiresConfirmation()
           ->modalHeading('Force translate')
           ->modalSubheading('It will take or less 5 to 10 min to process')
           ->modalButton('Confirm')
           ->action('save'));
       array_push($ss,parent::getFormActions()[1]);
      // dd(parent::getFormActions(),Action::make('aawqw'));
       return $ss; // TODO: Change the autogenerated stub
   }

    protected function aawqw(){

   }

    protected function getRedirectUrl(): string
    {

        if (!empty($this->record->parent_folder_id)){
            return route('filament.resources.folders.view',$this->record->id);
        }
        return route('filament.resources.folders.viewProject',$this->record->id);
    }
}
