<?php

namespace App\Filament\Resources\MailActivityResource\Pages;

use App\Filament\Resources\MailActivityResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Support\Facades\Cache;

class ListMailActivities extends ListRecords
{
    protected static string $resource = MailActivityResource::class;
    public function mount(): void
    {

        Cache::set('folder_id',request()->folder_id);
        parent::mount(); // TODO: Change the autogenerated stub
    }
    protected function getActions(): array
    {

        return [
            Actions\Action::make("Back")->label('Back')->url(route('filament.resources.folders.view',Cache::get('folder_id'))),
        ];
    }
}
