<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DynamicPromptResource\Pages;
use App\Filament\Resources\DynamicPromptResource\RelationManagers;
use App\Models\DynamicButton;
use App\Models\DynamicPrompt;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Cache;

class DynamicPromptResource extends Resource
{
    protected static ?string $model = DynamicPrompt::class;

    public static function canViewAny(): bool
    {
       // dd(\Illuminate\Support\Facades\Auth::user());
        return \Illuminate\Support\Facades\Auth::user()->plan->max_number_of_bot == '-1'; // TODO: Change the autogenerated stub
    }

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Hidden::make('folder_id')->default(Cache::get('folder_id')),
                Forms\Components\TagsInput::make('tags'),
                Forms\Components\Textarea::make('prompt')->rows(10)->columnSpanFull()

            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TagsColumn::make('tags')->searchable(),
                Tables\Columns\TextColumn::make('prompt')->limit(20)->searchable()

            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }
    public static function getEloquentQuery(): Builder
    {
        return DynamicPrompt::where('folder_id',Cache::get('folder_id')); // TODO: Change the autogenerated stub
    }
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDynamicPrompts::route('/'),
            'create' => Pages\CreateDynamicPrompt::route('/create'),
            'edit' => Pages\EditDynamicPrompt::route('/{record}/edit'),
        ];
    }
}
