<?php

namespace App\Filament\Resources;

use App\Filament\Resources\MailActivityResource\Pages;
use App\Filament\Resources\MailActivityResource\RelationManagers;
use App\Models\MailActivity;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Cache;

class MailActivityResource extends Resource
{
    protected static ?string $model = MailActivity::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('folder_id',Cache::get('folder_id'))->orderByDesc('id'); // TODO: Change the autogenerated stub
    }

   public static function canCreate(): bool
   {

       return false; // TODO: Change the autogenerated stub
   }

    public static function canEdit(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([

                Tables\Columns\TextColumn::make('created_at')->label('Date')->searchable(),
                Tables\Columns\TextColumn::make('log')->sortable()->searchable(),
            ])
            ->filters([
                //
            ])
            ->actions([
              //  Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                //Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMailActivities::route('/'),
            'create' => Pages\CreateMailActivity::route('/create'),
            'edit' => Pages\EditMailActivity::route('/{record}/edit'),
        ];
    }
}
