<?php

namespace App\Filament\Resources\DashboardResource\Widgets;

use App\Models\Company;
use App\Models\Folder;
use Filament\Tables\Columns\BadgeColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Filament\Widgets\TableWidget;
use Filament\Widgets\Widget;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Facades\Auth;

class FolderList  extends TableWidget
{
    protected static ?string $heading = "";

    public static function canView(): bool
    {
        if(\Illuminate\Support\Facades\Auth::user()->role == "user")
        return parent::canView(); // TODO: Change the autogenerated stub
        return false;
    }

    protected function getTableQuery(): \Illuminate\Database\Eloquent\Builder
    {
       $projects = Folder::where('company_id',Auth::user()->company->id)->whereNull('parent_folder_id')->pluck('id')->toArray();


        return Folder::whereIn('parent_folder_id',$projects)
            ->withCount(['contents'])
            ->with(['responseGpt3','responseGpt4','responseAll','media'])->orderby('name','asc');
    }

    protected function getTableColumns(): array
    {
        return [
//            TextColumn::make('id')->icon('heroicon-o-folder')->searchable(),
            TextColumn::make('name')->icon('heroicon-o-folder')->searchable(),
            BadgeColumn::make('contents_count')->colors(["primary"]),
            TextColumn::make('responseGpt3.number_of_response')->label('GPT3 response')->default('0')->searchable(),
            TextColumn::make('responseGpt4.number_of_response')->label('GPT4 response')->default('0')->searchable(),
            TextColumn::make('responseAll.number_of_clicks')->label('Click')->default('0'),
            TextColumn::make('mb')->default(
                function($record){
                    return number_format($record->mediaSize->sum('size')*0.000001,0);
                })->suffix('MB')->label('MB'),
        ];
    }

    protected int | string | array $columnSpan = 'full';
    protected static string $view = 'filament.resources.dashboard-resource.widgets.folder-list';
}
